name: Build and publish
run-name: ${{ github.actor }} - requested build

on:
  workflow_dispatch:

env:
  DOCKERFILE_LOCATION: ./Dockerfile
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # https://docs.github.com/en/actions/security-guides/automatic-token-authentication
  IMAGE_NAME: pgbouncer-docker
  REPO_TAG: 1.24.1
  # PAT_ORG_TOKEN: ${{ secrets.PAT_ORG_TOKEN }} # https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Metadata seeds
        id: seeds
        shell: bash
        run: |
          DATE=$(date +'%Y-%m-%d')
          echo shortref=${GITHUB_SHA:0:7} > $GITHUB_OUTPUT
          echo "date=$DATE"               >> $GITHUB_OUTPUT

      - name: Generating docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=auto
          tags: |
            type=raw,prefix=,suffix=,value=${{ steps.seeds.outputs.shortref }}
            type=raw,prefix=,suffix=,value=latest
            type=raw,prefix=,suffix=,value=pgbouncer-${{ env.REPO_TAG }}

          labels: |
            org.opencontainers.image.created=${{ steps.seeds.outputs.date }}
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
            org.opencontainers.image.source="https://github.com/${{ github.repository }}"
            org.opencontainers.image.description='Generated from automation.'
            pgbouncer.version=${{ env.REPO_TAG }}
            shortref=${{ steps.seeds.outputs.shortref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Context
        run: |
          docker context create builders || true
          docker context use default

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ env.DOCKERFILE_LOCATION }}
          build-args: |
            REPO_TAG=${{ env.REPO_TAG }}
          load: ${{ false }} # Will only build
          push: ${{ true }}  # Will build and push
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache,mode=max
          # secrets: ${{ secrets.GITHUB_TOKEN }}